words = ["school",
         "classroom",
         "curriculum",
         "chalkboard",
         "homework",
         "lesson",
         "study ",
         "lecture ",
         "student",
         "teach",
         "educational",
         "students",
         "classes",
         "kindergarten",
         "dormitory",
         "teacher",
         "math",
         "education",
         "playground",
         "semester", ]
